### PR TITLE
Social media website - Milestone: friendships v2

### PR DESCRIPTION
**Pull request by Emmyn5600**
## This pull request contains the following features:

* ### Added Add friend button to send a friend request.
      
* ##### (Note: Add friend button isn't visible to the user itself, it is only visible to the others so that he or she can send a request) to them.

* ### A user get notified that he or she has a pending friend request.

* ### I added accept and reject button to accept or reject user's friend request.

* ### Add friend button will change after a user sent a friend request with cancel request.

* ### After accepting someone's request you see unfriend button so that you can make unfriend with your friend.

* ### Added more test for testing all methods from models

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Emmyn5600 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the rspec testing! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.

Users got links to this [artcile](https://explainextended.com/2009/03/07/selecting-friends/) and [stackoverflow](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) discussion as a hint.
when friendship is confirmed, an additional row with reversed user-friend pair is created

- [ ]  thanks to this, we can find user friends only by user_id in friendships table
```
# User model
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

```
- [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model
# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

```
- [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model
# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

```

- [ ] In order to get all posts written by a user on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerable)
```
# User model
def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello there @Emmyn5600 👋🏾 👋🏾 I commend the effort you put in this project, keep it up 😄 However I cannot approve the project because you have not yet worked on all previously requested changes ⬇️ 

#### User model

- [ ]  thanks to this, we can find user friends only by user_id in the friendships table
```
has_many :friends, through: :confirmed_friendships
```

- [ ]  Users who requested to be friends (needed for notifications)
```
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [ ]  User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby). 
```
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
_If you have any questions, kindly leave a comment here and tag my name @mimipeshy and I will be glad to help_

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 

Hello, there @Emmyn5600 👋🏾 👋🏾 you have done so well in this milestone. You have worked on all TSE feedback given. Hence meeting all requirements needed. Therefore I approve of this milestone, go ahead and merge. All the best in the next milestone.

Regards
Peris Ndanu

**Review by Temmarie — COMMENTED** [review]
## STATUS: INVALID! :exclamation:
### Hi @Emmyn5600    ! :wave: :wave:

#### Good job completing your final project in the rails module :sunglasses::raised_hands: , however, I have to mark this submission as invalid because you skipped the following:

- [ ] You should have merged a PR from the development branch to the main/master branch with all changes made by you in previous milestones.

__Kindly make the necessary changes and submit another review.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
